name: Test, Lint, and Format

on: [push, pull_request]

jobs:
  main:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, MacOs, Windows]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get full python version
        id: full-python-version
        shell: bash
        run: echo ::set-output name=version::$(python -c "import sys; print('.'.join(str(v) for v in sys.version_info))")

      - name: Install poetry
        run: pip install poetry

      - name: Set Common venv Dir
        run: poetry config cache-dir $HOME/venv

      # By default poetry stores virtualenvs in different places on each major
      # system. This can be easily solved by storing the virtualenvs in the
      # project itself (`poetry config virtualenvs.in-project true`): however,
      # that poses the problem of all tools run against the repo including
      # everything in the virtualenv. So instead we just store in a common
      # location outside the repo to get the best of both worlds.
      # Note: That for windows, the only configuration for this to work is for
      #       the poetry cache-dir to be set using $HOME and the cache action
      #       to use ~. Otherwise poetry will create a directory called ~ or
      #       caching will try to interpret $HOME as a directory.
      - name: Set up cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/venv
          key: venv-v3-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

      - name: Run flake8
        run: |
            # Stop the build if there are Python syntax errors or undefined names
            poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics .
            # Error on warnings because I'm strict
            poetry run flake8 --count --statistics .

      - name: Run black
        run: poetry run black  --check .
